exp: TextClassification

mode: 
   - evaluate

models: 
    hf_text_classification_model:
        - /home/jnjoroge/nlp/nlp-final/model

datafpath: /home/jnjoroge/nlp/nlp-final/data/split_comm_data_test.tsv

predfpath:  /home/jnjoroge/nlp/nlp-final/predictions/preds2.tsv

resultsfpath: /home/jnjoroge/nlp/nlp-final/results/results2.tsv

numLabels: 2

id2label:
    0: Normal
    1: Exciting

batchsize: 64

checkFileColumns: True