exp: TextClassification

mode: 
   - train

models: 
    hf_text_classification_model:
        - google-bert/bert-base-cased

trainfpath: /home/jnjoroge/nlp/nlp-final/data/split_comm_data_train.tsv
validfpath: /home/jnjoroge/nlp/nlp-final/data/split_comm_data_validate.tsv

modelfpath:  /home/jnjoroge/nlp/nlp-final/model/

loadPretrained: False

epochs: 40

numLabels: 2

id2label:
    0: Normal
    1: Exciting

batchsize: 64
